version: '3'

services:
  app:
    build:
      context: ./app
    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    
    tty: true
    stdin_open: true
    read_only: false
    restart: 'no'
  
  db:
    build:
      context: ./db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "$$POSTGRES_DB" ]
      interval: 10s
      timeout: 60s
      retries: 10
      start_period: 80s

